// Generated by CoffeeScript 1.6.3
(function() {
  var app, cc, db, express;

  express = require('express');

  app = express();

  app.listen(process.env.PORT || 4040);

  cc = function(arg) {
    return console.log(arg);
  };

  db = require("mongojs").connect(process.env.MONGOHQ_URL || "JumboSmash", ['users']);

  app.configure(function() {
    app.use(express.logger('dev'));
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(express["static"](__dirname + '/public'));
  });

  app.get("/signup", function(req, res, next) {
    return res.render("signup");
  });

  app.post("/signup", function(req, res, next) {
    var click, email, year;
    click = req.body.submit_login;
    email = req.body.email;
    year = req.body.grad_year;
    if (typeof click !== "undefined") {
      db.users.insert({
        email: email,
        grad_year: year
      }, function(err, inserted) {
        if (err || !inserted) {
          return res.redirect("/signup?bad=true");
        } else {
          return res.redirect("/signup?bad=false");
        }
      });
      return true;
    }
    return res.redirect("/signup?bad=true");
  });

}).call(this);
